name: Build ESP32-S3 N16R8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v4.4.8

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'master-v4.3'
          submodules: 'recursive'
          fetch-depth: 0

      - name: Prepare and Build
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          
          git config --global --add safe.directory '*'

          git submodule update --init --recursive

          cat << 'EOF' >> sdkconfig.defaults
          CONFIG_IDF_TARGET="esp32s3"
          CONFIG_SPIRAM=y
          CONFIG_SPIRAM_MODE_OCT=y
          CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
          CONFIG_ESPTOOLPY_FLASHMODE_DIO=y
          EOF

          idf.py set-target esp32s3
          idf.py build

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: squeezelite-esp32s3-n16r8
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/ota_data_initial.bin
            build/squeezelite*.bin
