name: Build ESP32-S3 N16R8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v4.4.8

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Prepare and Build
        run: |
          pip install --upgrade pip
          pip install protobuf==4.25.6 grpcio-tools==1.62.3
          idf.py set-target esp32s3
          echo "CONFIG_IDF_TARGET=\"esp32s3\"" >> sdkconfig.defaults
          echo "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y" >> sdkconfig.defaults
          echo "CONFIG_SPIRAM_MODE_OCT=y" >> sdkconfig.defaults
          echo "CONFIG_ESPTOOLPY_FLASHMODE_DIO=y" >> sdkconfig.defaults
          idf.py build

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: squeezelite-esp32s3-n16r8
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/ota_data_initial.bin
            build/squeezelite*.bin
